const C={
mudanza:{f:[["home","Tipo de vivienda","s",[["room","Habitación"],["studio","Estudio"],["small","1-2 habitaciones"],["medium","3 habitaciones"],["large","4+ habitaciones"]]],["route","Ruta","s",[["city","Barcelona ciudad"],["metro","Área metropolitana"],["province","Provincia"]]],["floor","Planta más exigente","n"],["lift","Ascensor","s",[["yes","Sí"],["no","No"]]],["assembly","Desmontaje/montaje","s",[["no","No"],["yes","Sí"]]]],c:v=>{let x={room:[150,350],studio:[250,550],small:[400,900],medium:[700,1600],large:[1200,2500]}[v.home]||[400,900],m={city:1,metro:1.12,province:1.35}[v.route]||1;if(v.lift==="no"){x[0]+=(+v.floor||1)*25;x[1]+=(+v.floor||1)*45}if(v.assembly==="yes"){x[0]*=1.12;x[1]*=1.18}return[x[0]*m,x[1]*m]}},
porte:{f:[["items","Bultos/muebles","n"],["large","Pieza voluminosa","s",[["no","No"],["yes","Sí"]]],["floor","Planta sin ascensor","n"],["route","Ruta","s",[["city","Barcelona"],["metro","Área metropolitana"],["province","Provincia"]]]],c:v=>{let a=90+(+v.items||1)*10,b=140+(+v.items||1)*18;if(v.large==="yes"){a+=60;b+=110}a+=(+v.floor||0)*18;b+=(+v.floor||0)*30;let m={city:1,metro:1.15,province:1.35}[v.route]||1;return[a*m,b*m]}},
vaciado:{f:[["rooms","Estancias con contenido","n"],["density","Cantidad","s",[["low","Poco"],["medium","Normal"],["high","Muy cargado"]]],["floor","Planta","n"],["lift","Ascensor","s",[["yes","Sí"],["no","No"]]],["heavy","Piezas pesadas","s",[["no","No"],["yes","Sí"]]]],c:v=>{let r=Math.max(+v.rooms||1,1),m={low:.8,medium:1,high:1.45}[v.density]||1,a=150+r*55*m,b=230+r*95*m;if(v.lift==="no"){a+=(+v.floor||0)*20;b+=(+v.floor||0)*35}if(v.heavy==="yes"){a+=60;b+=120}return[a,b]}},
pintura:{f:[["sqm","m² de suelo","n"],["ceilings","Paredes y techos","s",[["yes","Sí"],["no","Solo paredes"]]],["condition","Estado","s",[["good","Bueno"],["normal","Reparaciones pequeñas"],["poor","Alisado/reparación importante"]]],["color","Cambio de color fuerte","s",[["no","No"],["yes","Sí"]]],["occupied","Piso","s",[["empty","Vacío"],["occupied","Con muebles"]]]],c:v=>{let m=Math.max(+v.sqm||40,20),r=v.ceilings==="yes"?[10,16]:[7,11],a=m*r[0],b=m*r[1];if(v.condition==="normal"){a*=1.15;b*=1.25}if(v.condition==="poor"){a*=1.45;b*=1.7}if(v.color==="yes"){a*=1.2;b*=1.3}if(v.occupied==="occupied"){a*=1.08;b*=1.15}return[a,b]}},
parquet:{f:[["sqm","m²","n"],["material","Material","s",[["laminate","Laminado AC4/AC5"],["multi","Multicapa"],["natural","Madera natural"]]],["remove","Retirar suelo","s",[["no","No"],["yes","Sí"]]],["level","Nivelar base","s",[["no","No"],["yes","Sí"]]]],c:v=>{let m=Math.max(+v.sqm||20,10),r={laminate:[25,45],multi:[65,85],natural:[70,120]}[v.material]||[25,45],a=m*r[0],b=m*r[1];if(v.remove==="yes"){a+=m*5;b+=m*12}if(v.level==="yes"){a+=m*6;b+=m*16}return[a,b]}},
limpieza:{f:[["sqm","m²","n"],["type","Tipo","s",[["delivery","Entrega/cambio inquilino"],["deep","A fondo"],["post","Fin de obra"]]],["state","Estado","s",[["light","Ligero"],["normal","Normal"],["heavy","Muy cargado"]]],["windows","Cristales","s",[["no","No"],["yes","Sí"]]]],c:v=>{let m=Math.max(+v.sqm||50,20),h=Math.max(3,m/12),r={delivery:[15,20],deep:[14,19],post:[16,22]}[v.type]||[15,20],z={light:.85,normal:1,heavy:1.35}[v.state]||1,a=h*r[0]*z,b=h*r[1]*z;if(v.windows==="yes"){a+=35;b+=90}return[a,b]}},
montaje:{f:[["items","Número de muebles","n"],["complex","Complejidad","s",[["simple","Sencillos"],["mixed","Mixtos"],["complex","Complejos"]]],["wall","Fijación pared","s",[["no","No"],["yes","Sí"]]],["remove","Desmontar antes","s",[["no","No"],["yes","Sí"]]]],c:v=>{let n=Math.max(+v.items||1,1),h=n*({simple:.65,mixed:1.1,complex:1.8}[v.complex]||1.1);if(v.wall==="yes")h+=.7;if(v.remove==="yes")h*=1.35;return[h*30,h*50]}},
reparaciones:{f:[["hours","Horas estimadas","n"],["jobs","Tareas distintas","n"],["materials","Materiales","s",[["low","Muy pocos"],["medium","Normales"],["high","Relevantes"]]]],c:v=>{let h=Math.max(+v.hours||1,1),a=h*35,b=h*55;if((+v.jobs||1)>2){a+=25;b+=50}if(v.materials==="medium"){a+=30;b+=80}if(v.materials==="high"){a+=80;b+=180}return[a,b]}},
carpinteria:{f:[["hours","Horas previstas","n"],["type","Tipo de trabajo","s",[["adjust","Ajuste/reparación"],["mount","Montaje"],["custom","A medida"]]]],c:v=>{let h=Math.max(+v.hours||1,1);return[h*16,h*27]}},
jardin:{f:[["size","Tamaño","s",[["small","Hasta 80 m²"],["medium","80–200 m²"],["large","200–400 m²"],["xl","Más de 400 m²"]]],["mode","Servicio","s",[["maintenance","Mantenimiento mensual"],["setup","Puesta a punto puntual"]]]],c:v=>v.mode==="maintenance"?({small:[130,180],medium:[170,300],large:[300,600],xl:[600,1100]}[v.size]||[170,300]):null,note:"Para puesta a punto puntual necesitamos revisar vegetación, estado y residuos. Referencia pública: una puesta a punto de 150 m² aparece alrededor de 300 €."},
finobra:{f:[["sqm","m²","n"],["state","Restos/manchas","s",[["light","Pocos"],["normal","Normales"],["heavy","Muchos"]]],["windows","Cristales","s",[["no","No"],["yes","Sí"]]]],c:v=>{let m=Math.max(+v.sqm||50,20),z={light:.8,normal:1,heavy:1.4}[v.state]||1,a=m*5*z,b=m*7*z;if(v.windows==="yes"){a+=40;b+=100}return[a,b]}},
escombros:{f:[["mode","Formato","s",[["sack","Sacos"],["bigbag","Big bag 1 m³"],["container","Contenedor 6 m³"]]],["units","Unidades","n"],["floor","Planta sin ascensor","n"]],c:v=>{let n=Math.max(+v.units||1,1),r={sack:[8,12],bigbag:[60,90],container:[120,220]}[v.mode]||[60,90],a=n*r[0],b=n*r[1];if((+v.floor||0)>0){a*=1.1;b*=1.2}return[a,b]}},
recogida:{f:[["items","Muebles/piezas","n"],["large","Piezas grandes","s",[["no","No"],["yes","Sí"]]],["floor","Planta sin ascensor","n"]],c:v=>{let n=Math.max(+v.items||1,1),a=80+n*12,b=130+n*22;if(v.large==="yes"){a+=50;b+=100}a+=(+v.floor||0)*18;b+=(+v.floor||0)*30;return[a,b]}},
diogenes:{review:true,f:[["sqm","m²","n"],["severity","Acumulación","s",[["low","Moderada"],["high","Alta"],["critical","Crítica / posible riesgo biológico"]]],["floor","Planta","n"]],note:"Por variabilidad y posible riesgo biológico, no cerramos precio automático. Referencia pública 2026: 600–2.500 € habitualmente, pudiendo superar 4.000 € en casos extremos. Requiere valoración técnica."},
hotel:{review:true,f:[["rooms","Habitaciones/estancias","n"],["scope","Alcance","s",[["furniture","Mobiliario"],["move","Traslado"],["turnover","Puesta a punto"]]],["night","Fuera de horario","s",[["no","No"],["yes","Sí"]]]],note:"Los proyectos hoteleros no tienen una tarifa pública homogénea fiable. Recogemos el alcance y pasamos a valoración técnica por fases."}
};
const E=n=>Math.round(n/10)*10;
document.querySelectorAll("[data-calculator]").forEach(h=>{let o=C[h.dataset.calculator];if(!o)return;h.innerHTML='<div class="calc-card"><form><div class="calc-grid"></div><button class="btn btn-accent">Ver orientación →</button><div class="calc-result" hidden></div><div class="calc-note">Estimación orientativa. No es presupuesto definitivo de Movipiso.</div></form></div>';let g=h.querySelector(".calc-grid");o.f.forEach(([n,l,t,op])=>{let w=document.createElement("label");w.textContent=l;let e=t==="s"?document.createElement("select"):document.createElement("input");e.name=n;if(t==="n"){e.type="number";e.min="0"}else op.forEach(([v,x])=>e.add(new Option(x,v)));w.append(e);g.append(w)});h.querySelector("form").onsubmit=e=>{e.preventDefault();let v=Object.fromEntries(new FormData(e.currentTarget)),r=h.querySelector(".calc-result");r.hidden=false;if(o.review){r.innerHTML="<strong>Valoración técnica necesaria</strong><p>"+o.note+"</p>";return}let out=o.c(v);if(!out){r.innerHTML="<strong>Valoración adicional</strong><p>"+o.note+"</p>";return}let[a,b]=out;r.innerHTML="<strong>"+E(a).toLocaleString("es-ES")+"–"+E(b).toLocaleString("es-ES")+" €</strong><p>Orientación inicial pendiente de validar alcance, acceso, materiales y requisitos aplicables.</p>"}});