(()=>{
const script=document.currentScript||[...document.scripts].find(s=>/site\.js/.test(s.src));const ROOT=script?new URL(".",script.src).href:new URL("./",location.href).href;const u=p=>new URL(p,ROOT).href;const px=id=>"https://images.pexels.com/photos/"+id+"/pexels-photo-"+id+".jpeg?auto=compress&cs=tinysrgb&w=1600";
const nav=`<div class="nav-v3">
<div class="nav-group"><button class="nav-trigger">Mudanzas</button><div class="nav-dropdown"><a href="${u("mudanzas/")}">Mudanzas</a><a href="${u("mini-mudanzas/")}">Mini mudanzas</a><a href="${u("portes/")}">Portes</a><a href="${u("vaciados/")}">Vaciados</a></div></div>
<div class="nav-group"><button class="nav-trigger">Servicios</button><div class="nav-dropdown services"><a href="${u("pintura/")}">Pintura</a><a href="${u("parquet/")}">Parquet</a><a href="${u("limpieza-fin-obra/")}">Limpieza fin de obra</a><a href="${u("limpieza/")}">Limpieza</a><a href="${u("montaje-muebles/")}">Montaje</a><a href="${u("carpinteria/")}">Carpintería</a><a href="${u("recogida-muebles/")}">Recogida muebles</a><a href="${u("retirada-escombros/")}">Escombros</a><a href="${u("limpieza-jardines/")}">Jardines</a><a href="${u("limpieza-diogenes/")}">Limpiezas especiales</a><a href="${u("pequenas-reparaciones/")}">Reparaciones</a><a href="${u("reformas/")}">Puesta a punto</a></div></div>
<div class="nav-group"><button class="nav-trigger">Zonas</button><div class="nav-dropdown"><a href="${u("zonas/")}">Cobertura</a><a href="${u("zonas/barcelona/")}">Barcelona</a><a href="${u("zonas/hospitalet/")}">L’Hospitalet</a><a href="${u("zonas/badalona/")}">Badalona</a><a href="${u("zonas/sabadell/")}">Sabadell</a><a href="${u("zonas/terrassa/")}">Terrassa</a></div></div>
<a class="nav-link-v3" href="${u("empresas/")}">Empresas</a><a class="nav-link-v3" href="${u("equipo/")}">Equipo</a><a class="nav-link-v3" href="${u("blog/")}">Blog</a></div>`;
document.querySelectorAll(".desktop-nav,.global-header nav").forEach(n=>n.innerHTML=nav);
const mobile=`<details><summary>Mudanzas</summary><a href="${u("mudanzas/")}">Mudanzas</a><a href="${u("mini-mudanzas/")}">Mini mudanzas</a><a href="${u("portes/")}">Portes</a><a href="${u("vaciados/")}">Vaciados</a></details><details><summary>Servicios</summary><a href="${u("pintura/")}">Pintura</a><a href="${u("parquet/")}">Parquet</a><a href="${u("limpieza-fin-obra/")}">Fin de obra</a><a href="${u("montaje-muebles/")}">Montaje</a><a href="${u("carpinteria/")}">Carpintería</a><a href="${u("recogida-muebles/")}">Recogida muebles</a><a href="${u("retirada-escombros/")}">Escombros</a><a href="${u("limpieza-jardines/")}">Jardines</a><a href="${u("limpieza-diogenes/")}">Limpiezas especiales</a></details><details><summary>Zonas</summary><a href="${u("zonas/barcelona/")}">Barcelona</a><a href="${u("zonas/hospitalet/")}">L’Hospitalet</a><a href="${u("zonas/badalona/")}">Badalona</a><a href="${u("zonas/sabadell/")}">Sabadell</a><a href="${u("zonas/terrassa/")}">Terrassa</a></details><a href="${u("empresas/")}">Empresas</a><a href="${u("equipo/")}">Equipo</a><a href="${u("blog/")}">Blog</a>`;
document.querySelectorAll(".mobile-nav,.mobile-menu").forEach(n=>n.innerHTML=mobile);
const b=document.querySelector("[data-nav-toggle],[data-menu-toggle]"),m=document.querySelector(".mobile-nav,.mobile-menu");if(b&&m)b.onclick=()=>{m.hidden=!m.hidden;b.setAttribute("aria-expanded",String(!m.hidden))};
document.querySelectorAll(".faq-list details").forEach(d=>d.addEventListener("toggle",()=>{if(d.open)d.closest(".faq-list").querySelectorAll("details").forEach(x=>{if(x!==d)x.open=false})}));
const io="IntersectionObserver"in window?new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add("is-visible");io.unobserve(e.target)}}),{threshold:.12}):null;const reveal=()=>document.querySelectorAll(".reveal-v3").forEach(x=>io?io.observe(x):x.classList.add("is-visible"));
const slug=location.pathname.split("/").filter(Boolean).filter(x=>x!=="movipiso-web").pop()||"";
const cfg={
mudanzas:["Una mudanza falla cuando se olvidan los accesos.","Inventario, planta, ascensor y calle forman parte del mismo trabajo.",7203787,["Volumen","Accesos","Ruta"],[["portes","Portes",5025669],["montaje-muebles","Montaje",7203699],["piso-listo","Piso Listo",4246115]]],
"mini-mudanzas":["Poco volumen no significa poca planificación.","Ajustamos medios al tamaño real del traslado.",7203820,["Pocas piezas","Acceso","Tiempo"],[["portes","Portes",8962877],["montaje-muebles","Montaje",6407553],["limpieza","Limpieza",7203883]]],
portes:["Una pieza puede ser todo el problema.","Medidas, peso, escalera y carga explican más que los kilómetros.",5025512,["Medidas","Peso","Ruta"],[["mini-mudanzas","Mini mudanzas",8939563],["montaje-muebles","Montaje",6169050],["recogida-muebles","Recogida",6407553]]],
vaciados:["Vaciar bien empieza por clasificar.","Qué sale, cuánto ocupa y por dónde baja.",4246110,["Volumen","Piezas pesadas","Salida"],[["recogida-muebles","Recogida",3791617],["limpieza","Limpieza",7203883],["piso-listo","Piso Listo",6347554]]],
pintura:["El acabado empieza antes del rodillo.","Estado, grietas y color definen la preparación.",5691694,["Superficie","Estado","Ocupación"],[["limpieza-fin-obra","Fin de obra",6474471],["parquet","Parquet",7218001],["piso-listo","Piso Listo",5691611]]],
parquet:["El material se ve; la base decide si dura.","Nivelación, retirada y soporte cambian el trabajo.",1388944,["Material","Base","Retirada"],[["pintura","Pintura",5767799],["montaje-muebles","Montaje",4226220],["reformas","Puesta a punto",7489125]]],
limpieza:["Limpiar antes de tiempo es limpiar dos veces.","La limpieza funciona mejor al final de la secuencia.",9462188,["Tipo","Estado","Cristales"],[["vaciados","Vaciado",7203883],["pintura","Pintura",7218001],["piso-listo","Piso Listo",4246110]]],
"montaje-muebles":["Una estantería y un armario no se calculan igual.","Complejidad, fijaciones y desmontaje mandan.",15016524,["Complejidad","Fijación","Desmontaje"],[["carpinteria","Carpintería",4226220],["portes","Portes",6474462],["parquet","Parquet",5767799]]],
"pequenas-reparaciones":["Agrupar incidencias reduce visitas.","Primero listamos; después asignamos la especialidad.",6474346,["Listado","Material","Especialidad"],[["carpinteria","Carpintería",5691515],["pintura","Pintura",5691597],["piso-listo","Piso Listo",31015267]]],
reformas:["La puesta a punto es una secuencia, no una lista de gremios.","Retirada, reparación, acabado y limpieza deben ir en orden.",5767799,["Alcance","Orden","Responsables"],[["pintura","Pintura",4263067],["parquet","Parquet",9462188],["limpieza","Limpieza",15016524]]],
empresas:["El coste oculto está en coordinar demasiados proveedores.","Una incidencia necesita responsable, evidencia y cierre.",7217852,["Incidencia","Evidencia","Recurrencia"],[["piso-listo","Piso Listo",7218515],["hoteles-b2b","Hoteles",31015267],["mudanzas","Traslados",7489125]]],
"piso-listo":["El gestor no quiere gremios: quiere el piso preparado.","La secuencia reduce tiempos muertos entre inquilinos.",4246110,["Llaves","Secuencia","Cierre"],[["vaciados","Vaciado",5691677],["pintura","Pintura",9462188],["limpieza","Limpieza",7489125]]]
};

carpinteria:["Una puerta que roza parece pequeña hasta que bloquea una entrega.","Ajuste, reparación y montaje necesitan material, herraje y estado real.",5691515,["Material","Herrajes","Horas"],[["montaje-muebles","Montaje",15016524],["pequenas-reparaciones","Reparaciones",6474346],["piso-listo","Piso Listo",31015267]]],
"limpieza-jardines":["Un jardín descuidado no se calcula solo por metros.","Vegetación, poda, residuos y acceso cambian completamente el trabajo.",1458694,["Superficie","Vegetación","Residuos"],[["limpieza","Limpieza",9462188],["retirada-escombros","Retirada",4246110],["empresas","Empresas",7217852]]],
"limpieza-fin-obra":["El final de obra empieza cuando termina el último gremio.","Polvo fino, cristales y restos requieren una limpieza distinta a la doméstica.",6474462,["Metros","Restos","Cristales"],[["pintura","Pintura",5691597],["retirada-escombros","Escombros",4246110],["reformas","Puesta a punto",5767799]]],
"recogida-muebles":["Retirar un mueble es logística, no simplemente cargarlo.","Medidas, planta y destino de retirada condicionan el servicio.",8939563,["Piezas","Acceso","Destino"],[["portes","Portes",5025512],["vaciados","Vaciados",7203788],["montaje-muebles","Montaje",15016524]]],
"retirada-escombros":["La runa ocupa poco en plano y mucho en la operativa.","Peso, formato, planta y destino autorizado son las variables críticas.",4246110,["Volumen","Peso","Retirada"],[["limpieza-fin-obra","Fin de obra",6474462],["reformas","Puesta a punto",5767799],["vaciados","Vaciados",7203788]]],
"limpieza-diogenes":["Aquí una calculadora cerrada sería irresponsable.","La acumulación y cualquier posible riesgo biológico exigen valoración técnica.",6195125,["Severidad","Riesgo","Protección"],[["vaciados","Vaciado",7203788],["limpieza","Limpieza",9462188],["empresas","Gestores",7217852]]],
"hoteles-b2b":["Un hotel no puede parar para mover mobiliario.","Planificación por fases, horarios y volumen por habitación son el centro del proyecto.",7218678,["Habitaciones","Fases","Horarios"],[["empresas","Empresas",7217852],["recogida-muebles","Retirada",8939563],["piso-listo","Piso Listo",31015267]]],
const main=document.querySelector("main"),calc=document.querySelector("#calculadora");if(main&&calc&&cfg[slug]&&!document.querySelector(".benchmark-extra")){const c=cfg[slug],sec=document.createElement("section");sec.className="benchmark-extra";sec.innerHTML=`<div class="shell benchmark-split"><div class="benchmark-media reveal-v3"><img src="${px(c[2])}" alt="" loading="lazy"></div><div class="benchmark-copy reveal-v3"><p class="kicker">EL RETO REAL</p><h2>${c[0]} <span>Lo resolvemos antes de empezar.</span></h2><p>${c[1]}</p><div class="pain-grid">${c[3].map(x=>'<div class="pain-card"><strong>'+x+'</strong><span>Variable que revisamos antes de cerrar alcance.</span></div>').join("")}</div></div></div>`;calc.before(sec);const proc=document.createElement("section");proc.className="benchmark-process";proc.innerHTML=`<div class="shell"><div class="section-head reveal-v3"><p class="kicker">PROCESO</p><h2>Cuatro pasos. Un seguimiento.</h2></div><div class="process-track-v3">${[["01","Cuéntanos","Ubicación, alcance y fecha."],["02","Dimensionamos","Calculadora + fotos/vídeo."],["03","Validamos","Medios, acceso y orden."],["04","Ejecutamos","Trabajo y cierre."]].map(x=>'<article class="process-v3 reveal-v3"><em>'+x[0]+'</em><strong>'+x[1]+'</strong><p>'+x[2]+'</p></article>').join("")}</div></div>`;calc.before(proc);const cross=document.createElement("section");cross.className="benchmark-cross";cross.innerHTML=`<div class="shell"><div class="section-head reveal-v3"><p class="kicker">CAPACIDAD TRANSVERSAL</p><h2>Si el trabajo no acaba aquí, <span>seguimos resolviendo.</span></h2></div><div class="cross-grid-v3">${c[4].map(x=>'<a class="cross-v3 reveal-v3" href="'+u(x[0]+'/')+'" style="--bg:url('+px(x[2])+')"><div><strong>'+x[1]+'</strong><span>Ver servicio →</span></div></a>').join("")}</div></div>`;calc.after(cross);const local=document.createElement("section");local.className="local-v3";local.innerHTML=`<div class="shell local-grid-v3"><div class="section-head reveal-v3"><p class="kicker">BARCELONA</p><h2>La zona orienta. <span>El acceso decide.</span></h2><p>Portal, ascensor, escaleras, calle y secuencia pueden cambiar el trabajo más que el código postal.</p></div><div class="local-points-v3">${["Acceso real","Vía pública","Edificio","Secuencia"].map(x=>'<div class="local-point-v3 reveal-v3"><strong>'+x+'</strong><span>Lo revisamos cuando afecta al alcance.</span></div>').join("")}</div></div>`;cross.after(local)}
const article=document.querySelector(".article-content");if(article&&!article.querySelector(".related-links")){const a=document.createElement("aside");a.className="related-links";a.innerHTML='<h3>Continúa por aquí</h3><div class="related-links-grid"><a href="'+u("mudanzas-barcelona/")+'">Mudanzas Barcelona →</a><a href="'+u("precios/")+'">Precios orientativos →</a><a href="'+u("blog/")+'">Más guías →</a></div>';article.append(a)}
reveal();
})();
(()=>{const script=document.currentScript||[...document.scripts].find(s=>/site\.js/.test(s.src));const ROOT=script?new URL(".",script.src).href:new URL("./",location.href).href;const u=p=>new URL(p,ROOT).href;const slug=location.pathname.split("/").filter(Boolean).filter(x=>x!=="movipiso-web").pop()||"";const map={
mudanzas:["Qué incluye de verdad","Protección básica, carga, transporte y descarga se explican por escrito. Desmontaje, embalaje o piezas especiales se añaden cuando hacen falta.",["Inventario","Acceso","Equipo","Entrega"]],
"mini-mudanzas":["Un servicio pequeño también necesita alcance","La diferencia está en dimensionar bien vehículo, tiempo y ayuda.",["Bultos","Ruta","Planta","Montaje"]],
portes:["Antes de mover una pieza, medimos el problema","Medidas, peso, escalera y carga explican más que los kilómetros.",["Medidas","Peso","Giros","Ruta"]],
vaciados:["Retirar no es abandonar","Separamos volumen, piezas especiales y destino de retirada.",["Volumen","Clasificación","Carga","Destino"]],
pintura:["Preparación antes de pintura","Estado de paredes, reparación, protección, manos y ocupación del piso forman parte del cálculo.",["Protección","Preparación","Acabado","Limpieza"]],
parquet:["El soporte importa tanto como el material","Retirada, nivelación, soporte y mobiliario se revisan antes de colocar.",["Material","Base","Rodapié","Muebles"]],
limpieza:["Definimos qué significa limpio","No es igual entrega de vivienda, limpieza profunda o fin de obra.",["Tipo","Estado","Cristales","Cierre"]],
"montaje-muebles":["Complejidad antes que número de cajas","Armarios, fijaciones y desmontaje previo cambian el tiempo.",["Piezas","Complejidad","Fijación","Desmontaje"]],
"pequenas-reparaciones":["Una lista única evita cinco visitas","Agrupamos tareas y separamos las que necesitan un especialista.",["Tareas","Material","Especialidad","Prioridad"]],
reformas:["Primero secuencia, luego gremios","Retirada, reparación, acabado, limpieza y montaje deben ir en orden.",["Alcance","Orden","Dependencias","Cierre"]],
empresas:["Trazabilidad para quien gestiona","Cada incidencia necesita responsable, evidencia y cierre.",["Entrada","Responsable","Evidencia","Cierre"]],
"piso-listo":["La llave marca el inicio; la entrega marca el final","Piso Listo se diseña para rotación de vivienda.",["Llaves","Revisión","Ejecución","Entrega"]],
carpinteria:["Ajustar antes de sustituir","Puertas, bisagras, herrajes y pequeños trabajos se diagnostican antes.",["Diagnóstico","Herraje","Ajuste","Acabado"]],
"limpieza-jardines":["Los metros no cuentan toda la historia","Vegetación, altura, residuos verdes y acceso pesan en el trabajo.",["Superficie","Poda","Residuos","Acceso"]],
"limpieza-fin-obra":["El polvo fino no se trata como polvo doméstico","Restos, superficies y cristales requieren otro protocolo.",["Restos","Polvo fino","Cristales","Entrega"]],
"recogida-muebles":["Primero decidimos el destino","Reutilización, reciclaje o retirada condicionan la operativa.",["Estado","Medidas","Acceso","Destino"]],
"retirada-escombros":["Peso, volumen y legalidad","Tipo de residuo, embalaje, acceso y destino deben estar claros.",["Tipo","Volumen","Carga","Destino"]],
"limpieza-diogenes":["Valoración humana y técnica","No automatizamos un precio en situaciones de acumulación extrema o posible riesgo biológico.",["Seguridad","EPIs","Volumen","Protocolo"]],
"hoteles-b2b":["Trabajar sin bloquear la operación","En hoteles importan fases, horarios, ascensores de servicio y habitaciones.",["Fases","Horarios","Volumen","Continuidad"]]
};const cfg=map[slug],faq=document.querySelector(".faq-list");if(!cfg||!faq||document.querySelector(".service-depth-v3"))return;const sec=document.createElement("section");sec.className="service-depth-v3";sec.innerHTML='<div class="shell depth-grid-v3"><div class="depth-copy-v3 reveal-v3"><p class="kicker">ALCANCE CLARO</p><h2>'+cfg[0]+'</h2><p>'+cfg[1]+'</p><a class="btn btn-blue" href="'+u("contacto/")+'">Pedir valoración →</a></div><div class="depth-list-v3">'+cfg[2].map((x,i)=>'<div class="depth-item-v3 reveal-v3"><span>0'+(i+1)+'</span><strong>'+x+'</strong><small>Se valida antes de cerrar el trabajo.</small></div>').join("")+'</div></div>';faq.closest(".section").before(sec)})();

/* ARTICLE FAQ V5 · mantiene el contenido en HTML y lo convierte visualmente en desplegable */
(()=>{document.querySelectorAll(".article-content h2#faq").forEach(head=>{
 if(head.nextElementSibling?.classList?.contains("article-faq-list"))return;
 const box=document.createElement("div");box.className="article-faq-list faq-list";
 let node=head.nextElementSibling;
 while(node&&node.tagName!=="H2"){
   const next=node.nextElementSibling;
   if(node.tagName==="H3"){
     const p=next&&next.tagName==="P"?next:null;
     const d=document.createElement("details"),s=document.createElement("summary");
     s.innerHTML=node.innerHTML;d.append(s);
     if(p){d.append(p);node.remove();node=p.nextElementSibling}else{node.remove();node=next}
     box.append(d);continue;
   }
   node=next;
 }
 head.insertAdjacentElement("afterend",box);
});})();
